package model

// !!! DO NOT EDIT THIS FILE

import (
	"context"
	"encoding/json"
	"github.com/iancoleman/strcase"
	"github.com/mylxsw/eloquent/query"
	"gopkg.in/guregu/null.v3"
	"time"
)

func init() {

}

// QuotaStatisticsN is a QuotaStatistics object, all fields are nullable
type QuotaStatisticsN struct {
	original             *quotaStatisticsOriginal
	quotaStatisticsModel *QuotaStatisticsModel

	Id        null.Int  `json:"id"`
	UserId    null.Int  `json:"user_id"`
	Used      null.Int  `json:"used"`
	CalDate   null.Time `json:"cal_date"`
	CreatedAt null.Time
	UpdatedAt null.Time
}

// As convert object to other type
// dst must be a pointer to struct
func (inst *QuotaStatisticsN) As(dst interface{}) error {
	return query.Copy(inst, dst)
}

// SetModel set model for QuotaStatistics
func (inst *QuotaStatisticsN) SetModel(quotaStatisticsModel *QuotaStatisticsModel) {
	inst.quotaStatisticsModel = quotaStatisticsModel
}

// quotaStatisticsOriginal is an object which stores original QuotaStatistics from database
type quotaStatisticsOriginal struct {
	Id        null.Int
	UserId    null.Int
	Used      null.Int
	CalDate   null.Time
	CreatedAt null.Time
	UpdatedAt null.Time
}

// Staled identify whether the object has been modified
func (inst *QuotaStatisticsN) Staled(onlyFields ...string) bool {
	if inst.original == nil {
		inst.original = &quotaStatisticsOriginal{}
	}

	if len(onlyFields) == 0 {

		if inst.Id != inst.original.Id {
			return true
		}
		if inst.UserId != inst.original.UserId {
			return true
		}
		if inst.Used != inst.original.Used {
			return true
		}
		if inst.CalDate != inst.original.CalDate {
			return true
		}
		if inst.CreatedAt != inst.original.CreatedAt {
			return true
		}
		if inst.UpdatedAt != inst.original.UpdatedAt {
			return true
		}
	} else {
		for _, f := range onlyFields {
			switch strcase.ToSnake(f) {

			case "id":
				if inst.Id != inst.original.Id {
					return true
				}
			case "user_id":
				if inst.UserId != inst.original.UserId {
					return true
				}
			case "used":
				if inst.Used != inst.original.Used {
					return true
				}
			case "cal_date":
				if inst.CalDate != inst.original.CalDate {
					return true
				}
			case "created_at":
				if inst.CreatedAt != inst.original.CreatedAt {
					return true
				}
			case "updated_at":
				if inst.UpdatedAt != inst.original.UpdatedAt {
					return true
				}
			default:
			}
		}
	}

	return false
}

// StaledKV return all fields has been modified
func (inst *QuotaStatisticsN) StaledKV(onlyFields ...string) query.KV {
	kv := make(query.KV, 0)

	if inst.original == nil {
		inst.original = &quotaStatisticsOriginal{}
	}

	if len(onlyFields) == 0 {

		if inst.Id != inst.original.Id {
			kv["id"] = inst.Id
		}
		if inst.UserId != inst.original.UserId {
			kv["user_id"] = inst.UserId
		}
		if inst.Used != inst.original.Used {
			kv["used"] = inst.Used
		}
		if inst.CalDate != inst.original.CalDate {
			kv["cal_date"] = inst.CalDate
		}
		if inst.CreatedAt != inst.original.CreatedAt {
			kv["created_at"] = inst.CreatedAt
		}
		if inst.UpdatedAt != inst.original.UpdatedAt {
			kv["updated_at"] = inst.UpdatedAt
		}
	} else {
		for _, f := range onlyFields {
			switch strcase.ToSnake(f) {

			case "id":
				if inst.Id != inst.original.Id {
					kv["id"] = inst.Id
				}
			case "user_id":
				if inst.UserId != inst.original.UserId {
					kv["user_id"] = inst.UserId
				}
			case "used":
				if inst.Used != inst.original.Used {
					kv["used"] = inst.Used
				}
			case "cal_date":
				if inst.CalDate != inst.original.CalDate {
					kv["cal_date"] = inst.CalDate
				}
			case "created_at":
				if inst.CreatedAt != inst.original.CreatedAt {
					kv["created_at"] = inst.CreatedAt
				}
			case "updated_at":
				if inst.UpdatedAt != inst.original.UpdatedAt {
					kv["updated_at"] = inst.UpdatedAt
				}
			default:
			}
		}
	}

	return kv
}

// Save create a new model or update it
func (inst *QuotaStatisticsN) Save(ctx context.Context, onlyFields ...string) error {
	if inst.quotaStatisticsModel == nil {
		return query.ErrModelNotSet
	}

	id, _, err := inst.quotaStatisticsModel.SaveOrUpdate(ctx, *inst, onlyFields...)
	if err != nil {
		return err
	}

	inst.Id = null.IntFrom(id)
	return nil
}

// Delete remove a quota_statistics
func (inst *QuotaStatisticsN) Delete(ctx context.Context) error {
	if inst.quotaStatisticsModel == nil {
		return query.ErrModelNotSet
	}

	_, err := inst.quotaStatisticsModel.DeleteById(ctx, inst.Id.Int64)
	if err != nil {
		return err
	}

	return nil
}

// String convert instance to json string
func (inst *QuotaStatisticsN) String() string {
	rs, _ := json.Marshal(inst)
	return string(rs)
}

type quotaStatisticsScope struct {
	name  string
	apply func(builder query.Condition)
}

var quotaStatisticsGlobalScopes = make([]quotaStatisticsScope, 0)
var quotaStatisticsLocalScopes = make([]quotaStatisticsScope, 0)

// AddGlobalScopeForQuotaStatistics assign a global scope to a model
func AddGlobalScopeForQuotaStatistics(name string, apply func(builder query.Condition)) {
	quotaStatisticsGlobalScopes = append(quotaStatisticsGlobalScopes, quotaStatisticsScope{name: name, apply: apply})
}

// AddLocalScopeForQuotaStatistics assign a local scope to a model
func AddLocalScopeForQuotaStatistics(name string, apply func(builder query.Condition)) {
	quotaStatisticsLocalScopes = append(quotaStatisticsLocalScopes, quotaStatisticsScope{name: name, apply: apply})
}

func (m *QuotaStatisticsModel) applyScope() query.Condition {
	scopeCond := query.ConditionBuilder()
	for _, g := range quotaStatisticsGlobalScopes {
		if m.globalScopeEnabled(g.name) {
			g.apply(scopeCond)
		}
	}

	for _, s := range quotaStatisticsLocalScopes {
		if m.localScopeEnabled(s.name) {
			s.apply(scopeCond)
		}
	}

	return scopeCond
}

func (m *QuotaStatisticsModel) localScopeEnabled(name string) bool {
	for _, n := range m.includeLocalScopes {
		if name == n {
			return true
		}
	}

	return false
}

func (m *QuotaStatisticsModel) globalScopeEnabled(name string) bool {
	for _, n := range m.excludeGlobalScopes {
		if name == n {
			return false
		}
	}

	return true
}

type QuotaStatistics struct {
	Id        int64     `json:"id"`
	UserId    int64     `json:"user_id"`
	Used      int64     `json:"used"`
	CalDate   time.Time `json:"cal_date"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (w QuotaStatistics) ToQuotaStatisticsN(allows ...string) QuotaStatisticsN {
	if len(allows) == 0 {
		return QuotaStatisticsN{

			Id:        null.IntFrom(int64(w.Id)),
			UserId:    null.IntFrom(int64(w.UserId)),
			Used:      null.IntFrom(int64(w.Used)),
			CalDate:   null.TimeFrom(w.CalDate),
			CreatedAt: null.TimeFrom(w.CreatedAt),
			UpdatedAt: null.TimeFrom(w.UpdatedAt),
		}
	}

	res := QuotaStatisticsN{}
	for _, al := range allows {
		switch strcase.ToSnake(al) {

		case "id":
			res.Id = null.IntFrom(int64(w.Id))
		case "user_id":
			res.UserId = null.IntFrom(int64(w.UserId))
		case "used":
			res.Used = null.IntFrom(int64(w.Used))
		case "cal_date":
			res.CalDate = null.TimeFrom(w.CalDate)
		case "created_at":
			res.CreatedAt = null.TimeFrom(w.CreatedAt)
		case "updated_at":
			res.UpdatedAt = null.TimeFrom(w.UpdatedAt)
		default:
		}
	}

	return res
}

// As convert object to other type
// dst must be a pointer to struct
func (w QuotaStatistics) As(dst interface{}) error {
	return query.Copy(w, dst)
}

func (w *QuotaStatisticsN) ToQuotaStatistics() QuotaStatistics {
	return QuotaStatistics{

		Id:        w.Id.Int64,
		UserId:    w.UserId.Int64,
		Used:      w.Used.Int64,
		CalDate:   w.CalDate.Time,
		CreatedAt: w.CreatedAt.Time,
		UpdatedAt: w.UpdatedAt.Time,
	}
}

// QuotaStatisticsModel is a model which encapsulates the operations of the object
type QuotaStatisticsModel struct {
	db        *query.DatabaseWrap
	tableName string

	excludeGlobalScopes []string
	includeLocalScopes  []string

	query query.SQLBuilder
}

var quotaStatisticsTableName = "quota_statistics"

// QuotaStatisticsTable return table name for QuotaStatistics
func QuotaStatisticsTable() string {
	return quotaStatisticsTableName
}

const (
	FieldQuotaStatisticsId        = "id"
	FieldQuotaStatisticsUserId    = "user_id"
	FieldQuotaStatisticsUsed      = "used"
	FieldQuotaStatisticsCalDate   = "cal_date"
	FieldQuotaStatisticsCreatedAt = "created_at"
	FieldQuotaStatisticsUpdatedAt = "updated_at"
)

// QuotaStatisticsFields return all fields in QuotaStatistics model
func QuotaStatisticsFields() []string {
	return []string{
		"id",
		"user_id",
		"used",
		"cal_date",
		"created_at",
		"updated_at",
	}
}

func SetQuotaStatisticsTable(tableName string) {
	quotaStatisticsTableName = tableName
}

// NewQuotaStatisticsModel create a QuotaStatisticsModel
func NewQuotaStatisticsModel(db query.Database) *QuotaStatisticsModel {
	return &QuotaStatisticsModel{
		db:                  query.NewDatabaseWrap(db),
		tableName:           quotaStatisticsTableName,
		excludeGlobalScopes: make([]string, 0),
		includeLocalScopes:  make([]string, 0),
		query:               query.Builder(),
	}
}

// GetDB return database instance
func (m *QuotaStatisticsModel) GetDB() query.Database {
	return m.db.GetDB()
}

func (m *QuotaStatisticsModel) clone() *QuotaStatisticsModel {
	return &QuotaStatisticsModel{
		db:                  m.db,
		tableName:           m.tableName,
		excludeGlobalScopes: append([]string{}, m.excludeGlobalScopes...),
		includeLocalScopes:  append([]string{}, m.includeLocalScopes...),
		query:               m.query,
	}
}

// WithoutGlobalScopes remove a global scope for given query
func (m *QuotaStatisticsModel) WithoutGlobalScopes(names ...string) *QuotaStatisticsModel {
	mc := m.clone()
	mc.excludeGlobalScopes = append(mc.excludeGlobalScopes, names...)

	return mc
}

// WithLocalScopes add a local scope for given query
func (m *QuotaStatisticsModel) WithLocalScopes(names ...string) *QuotaStatisticsModel {
	mc := m.clone()
	mc.includeLocalScopes = append(mc.includeLocalScopes, names...)

	return mc
}

// Condition add query builder to model
func (m *QuotaStatisticsModel) Condition(builder query.SQLBuilder) *QuotaStatisticsModel {
	mm := m.clone()
	mm.query = mm.query.Merge(builder)

	return mm
}

// Find retrieve a model by its primary key
func (m *QuotaStatisticsModel) Find(ctx context.Context, id int64) (*QuotaStatisticsN, error) {
	return m.First(ctx, m.query.Where("id", "=", id))
}

// Exists return whether the records exists for a given query
func (m *QuotaStatisticsModel) Exists(ctx context.Context, builders ...query.SQLBuilder) (bool, error) {
	count, err := m.Count(ctx, builders...)
	return count > 0, err
}

// Count return model count for a given query
func (m *QuotaStatisticsModel) Count(ctx context.Context, builders ...query.SQLBuilder) (int64, error) {
	sqlStr, params := m.query.
		Merge(builders...).
		Table(m.tableName).
		AppendCondition(m.applyScope()).
		ResolveCount()

	rows, err := m.db.QueryContext(ctx, sqlStr, params...)
	if err != nil {
		return 0, err
	}

	defer rows.Close()

	rows.Next()
	var res int64
	if err := rows.Scan(&res); err != nil {
		return 0, err
	}

	return res, nil
}

func (m *QuotaStatisticsModel) Paginate(ctx context.Context, page int64, perPage int64, builders ...query.SQLBuilder) ([]QuotaStatisticsN, query.PaginateMeta, error) {
	if page <= 0 {
		page = 1
	}

	if perPage <= 0 {
		perPage = 15
	}

	meta := query.PaginateMeta{
		PerPage: perPage,
		Page:    page,
	}

	count, err := m.Count(ctx, builders...)
	if err != nil {
		return nil, meta, err
	}

	meta.Total = count
	meta.LastPage = count / perPage
	if count%perPage != 0 {
		meta.LastPage += 1
	}

	res, err := m.Get(ctx, append([]query.SQLBuilder{query.Builder().Limit(perPage).Offset((page - 1) * perPage)}, builders...)...)
	if err != nil {
		return res, meta, err
	}

	return res, meta, nil
}

// Get retrieve all results for given query
func (m *QuotaStatisticsModel) Get(ctx context.Context, builders ...query.SQLBuilder) ([]QuotaStatisticsN, error) {
	b := m.query.Merge(builders...).Table(m.tableName).AppendCondition(m.applyScope())
	if len(b.GetFields()) == 0 {
		b = b.Select(
			"id",
			"user_id",
			"used",
			"cal_date",
			"created_at",
			"updated_at",
		)
	}

	fields := b.GetFields()
	selectFields := make([]query.Expr, 0)

	for _, f := range fields {
		switch strcase.ToSnake(f.Value) {

		case "id":
			selectFields = append(selectFields, f)
		case "user_id":
			selectFields = append(selectFields, f)
		case "used":
			selectFields = append(selectFields, f)
		case "cal_date":
			selectFields = append(selectFields, f)
		case "created_at":
			selectFields = append(selectFields, f)
		case "updated_at":
			selectFields = append(selectFields, f)
		}
	}

	var createScanVar = func(fields []query.Expr) (*QuotaStatisticsN, []interface{}) {
		var quotaStatisticsVar QuotaStatisticsN
		scanFields := make([]interface{}, 0)

		for _, f := range fields {
			switch strcase.ToSnake(f.Value) {

			case "id":
				scanFields = append(scanFields, &quotaStatisticsVar.Id)
			case "user_id":
				scanFields = append(scanFields, &quotaStatisticsVar.UserId)
			case "used":
				scanFields = append(scanFields, &quotaStatisticsVar.Used)
			case "cal_date":
				scanFields = append(scanFields, &quotaStatisticsVar.CalDate)
			case "created_at":
				scanFields = append(scanFields, &quotaStatisticsVar.CreatedAt)
			case "updated_at":
				scanFields = append(scanFields, &quotaStatisticsVar.UpdatedAt)
			}
		}

		return &quotaStatisticsVar, scanFields
	}

	sqlStr, params := b.Fields(selectFields...).ResolveQuery()

	rows, err := m.db.QueryContext(ctx, sqlStr, params...)
	if err != nil {
		return nil, err
	}

	defer rows.Close()

	quotaStatisticss := make([]QuotaStatisticsN, 0)
	for rows.Next() {
		quotaStatisticsReal, scanFields := createScanVar(fields)
		if err := rows.Scan(scanFields...); err != nil {
			return nil, err
		}

		quotaStatisticsReal.original = &quotaStatisticsOriginal{}
		_ = query.Copy(quotaStatisticsReal, quotaStatisticsReal.original)

		quotaStatisticsReal.SetModel(m)
		quotaStatisticss = append(quotaStatisticss, *quotaStatisticsReal)
	}

	return quotaStatisticss, nil
}

// First return first result for given query
func (m *QuotaStatisticsModel) First(ctx context.Context, builders ...query.SQLBuilder) (*QuotaStatisticsN, error) {
	res, err := m.Get(ctx, append(builders, query.Builder().Limit(1))...)
	if err != nil {
		return nil, err
	}

	if len(res) == 0 {
		return nil, query.ErrNoResult
	}

	return &res[0], nil
}

// Create save a new quota_statistics to database
func (m *QuotaStatisticsModel) Create(ctx context.Context, kv query.KV) (int64, error) {

	if _, ok := kv["created_at"]; !ok {
		kv["created_at"] = time.Now()
	}

	if _, ok := kv["updated_at"]; !ok {
		kv["updated_at"] = time.Now()
	}

	sqlStr, params := m.query.Table(m.tableName).ResolveInsert(kv)

	res, err := m.db.ExecContext(ctx, sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.LastInsertId()
}

// SaveAll save all quota_statisticss to database
func (m *QuotaStatisticsModel) SaveAll(ctx context.Context, quotaStatisticss []QuotaStatisticsN) ([]int64, error) {
	ids := make([]int64, 0)
	for _, quotaStatistics := range quotaStatisticss {
		id, err := m.Save(ctx, quotaStatistics)
		if err != nil {
			return ids, err
		}

		ids = append(ids, id)
	}

	return ids, nil
}

// Save save a quota_statistics to database
func (m *QuotaStatisticsModel) Save(ctx context.Context, quotaStatistics QuotaStatisticsN, onlyFields ...string) (int64, error) {
	return m.Create(ctx, quotaStatistics.StaledKV(onlyFields...))
}

// SaveOrUpdate save a new quota_statistics or update it when it has a id > 0
func (m *QuotaStatisticsModel) SaveOrUpdate(ctx context.Context, quotaStatistics QuotaStatisticsN, onlyFields ...string) (id int64, updated bool, err error) {
	if quotaStatistics.Id.Int64 > 0 {
		_, _err := m.UpdateById(ctx, quotaStatistics.Id.Int64, quotaStatistics, onlyFields...)
		return quotaStatistics.Id.Int64, true, _err
	}

	_id, _err := m.Save(ctx, quotaStatistics, onlyFields...)
	return _id, false, _err
}

// UpdateFields update kv for a given query
func (m *QuotaStatisticsModel) UpdateFields(ctx context.Context, kv query.KV, builders ...query.SQLBuilder) (int64, error) {
	if len(kv) == 0 {
		return 0, nil
	}

	kv["updated_at"] = time.Now()

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).
		Table(m.tableName).
		ResolveUpdate(kv)

	res, err := m.db.ExecContext(ctx, sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()
}

// Update update a model for given query
func (m *QuotaStatisticsModel) Update(ctx context.Context, builder query.SQLBuilder, quotaStatistics QuotaStatisticsN, onlyFields ...string) (int64, error) {
	return m.UpdateFields(ctx, quotaStatistics.StaledKV(onlyFields...), builder)
}

// UpdateById update a model by id
func (m *QuotaStatisticsModel) UpdateById(ctx context.Context, id int64, quotaStatistics QuotaStatisticsN, onlyFields ...string) (int64, error) {
	return m.Condition(query.Builder().Where("id", "=", id)).UpdateFields(ctx, quotaStatistics.StaledKV(onlyFields...))
}

// Delete remove a model
func (m *QuotaStatisticsModel) Delete(ctx context.Context, builders ...query.SQLBuilder) (int64, error) {

	sqlStr, params := m.query.Merge(builders...).AppendCondition(m.applyScope()).Table(m.tableName).ResolveDelete()

	res, err := m.db.ExecContext(ctx, sqlStr, params...)
	if err != nil {
		return 0, err
	}

	return res.RowsAffected()

}

// DeleteById remove a model by id
func (m *QuotaStatisticsModel) DeleteById(ctx context.Context, id int64) (int64, error) {
	return m.Condition(query.Builder().Where("id", "=", id)).Delete(ctx)
}
