package getimgai

func GetModelByID(id string) *Model {
	for _, model := range Models {
		if model.ID == id {
			return &model
		}
	}
	return nil
}

const (
	ModelFamilySDXL = "stable-diffusion-xl"
)

var Models = []Model{
	{
		ID:             "stable-diffusion-xl-v1-0",
		Name:           "Stable Diffusion XL",
		Family:         "stable-diffusion-xl",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 1024, Height: 1024},
		Price:          0.0003,
		AuthorURL:      "https://stability.ai",
		LicenseURL:     "https://getimg.ai/legal/stable-diffusion-xl-license",
	},
	{
		ID:             "synthwave-punk-v2",
		Name:           "SynthwavePunk v2",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://github.com/JustMaier",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "arcane-diffusion",
		Name:           "Arcane Diffusion",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://twitter.com/Nitrosocke",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "moonfilm-reality-v3",
		Name:           "MoonFilm Reality v3",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://ko-fi.com/leopasama",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "moonfilm-utopia-v3",
		Name:           "MoonFilm Utopia v3",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://ko-fi.com/leopasama",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "moonfilm-film-grain-v1",
		Name:           "MoonFilm FilmGrain v1",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://ko-fi.com/leopasama",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "openjourney-v4",
		Name:           "Openjourney v4",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://prompthero.com/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "realistic-vision-v3",
		Name:           "Realistic Vision v3",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/SG_161222",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "icbinp-final",
		Name:           "ICBINP Final",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/residentchiefnz",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "icbinp-relapse",
		Name:           "ICBINP Relapse",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/residentchiefnz",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "icbinp-afterburn",
		Name:           "ICBINP Afterburn",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/residentchiefnz",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "xsarchitectural-interior-design",
		Name:           "InteriorDesign",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/Xsarchitectural",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "mo-di-diffusion",
		Name:           "Modern Disney Diffusion",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://twitter.com/Nitrosocke",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "anashel-rpg",
		Name:           "RPG",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://huggingface.co/Anashel",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "realistic-vision-v1-3-inpainting",
		Name:           "Realistic Vision v1.3 Inpainting",
		Family:         "stable-diffusion",
		Pipelines:      []string{"inpaint"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000550,
		AuthorURL:      "https://civitai.com/user/SG_161222",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "eimis-anime-diffusion-v1-0",
		Name:           "Anime Diffusion",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://huggingface.co/eimiss",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "something-v2-2",
		Name:           "Something V2.2",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://twitter.com/nocrypt_",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "icbinp",
		Name:           "ICBINP",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/residentchiefnz",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "analog-diffusion",
		Name:           "Analog Diffusion",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://twitter.com/wavymulder",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "neverending-dream",
		Name:           "NeverEnding Dream",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://www.buymeacoffee.com/lykon",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "van-gogh-diffusion",
		Name:           "Van Gogh Diffusion",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://huggingface.co/dallinmackay",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "openjourney-v1-0",
		Name:           "Openjourney",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://prompthero.com/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "realistic-vision-v1-3",
		Name:           "Realistic Vision v1.3",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://civitai.com/user/SG_161222",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "stable-diffusion-v1-5-inpainting",
		Name:           "Stable Diffusion Inpainting v1.5",
		Family:         "stable-diffusion",
		Pipelines:      []string{"inpaint"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000550,
		AuthorURL:      "https://runwayml.com/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "gfpgan-v1-3",
		Name:           "GFPGAN v1.3",
		Family:         "enhacements",
		Pipelines:      []string{"face-fix"},
		BaseResolution: ModelResolution{Width: 0, Height: 0},
		Price:          0.020000,
		AuthorURL:      "https://arc.tencent.com/zh/index",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "real-esrgan-4x",
		Name:           "Real-ESRGAN",
		Family:         "enhacements",
		Pipelines:      []string{"upscale"},
		BaseResolution: ModelResolution{Width: 0, Height: 0},
		Price:          0.005500,
		AuthorURL:      "https://xinntao.github.io/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "instruct-pix2pix",
		Name:           "Instruct Pix2Pix",
		Family:         "stable-diffusion",
		Pipelines:      []string{"instruct"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://www.timothybrooks.com/about/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "stable-diffusion-v2-1",
		Name:           "Stable Diffusion v2.1",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image"},
		BaseResolution: ModelResolution{Width: 768, Height: 768},
		Price:          0.000400,
		AuthorURL:      "https://stability.ai/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
	{
		ID:             "stable-diffusion-v1-5",
		Name:           "Stable Diffusion v1.5",
		Family:         "stable-diffusion",
		Pipelines:      []string{"text-to-image", "image-to-image", "controlnet"},
		BaseResolution: ModelResolution{Width: 512, Height: 512},
		Price:          0.000450,
		AuthorURL:      "https://runwayml.com/",
		LicenseURL:     "https://huggingface.co/spaces/CompVis/stable-diffusion-license",
	},
}
